name: c++-checks

on:
  pull_request:
    branches: main
  push:
    branches: main

env:
  # (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  cc-build-format-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: checkout data
      run: git lfs checkout

    - name: install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libgl1-mesa-dev

    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} cc/

    - name: build
      run: cmake --build -j 2 ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: test
      working-directory: ${{github.workspace}}/build
      run: |
        make unit
        cat unit_tests_output.txt
        

    # - name: upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: unit_tests_output.txt
