name: c++-checks

on:
  pull_request:
    branches: main
  push:
    branches: main

env:
  # (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  cc-build-format-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: checkout data
      run: git lfs checkout

    - name: install dev dependencies
      run: |
        dev/setup.sh

    - name: check format
      run: |
        dev/check-format.sh

    - name: configure
      run: |
        cmake -B ${{github.workspace}}/build/debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake -B ${{github.workspace}}/build/coverage

    - name: build
      working-directory: ${{github.workspace}}/build/debug
      run: make -j 2

    - name: create test files
      working-directory: ${{github.workspace}}
      run: |
        cmake -B ${{github.workspace}}/build/release -DCMAKE_BUILD_TYPE=Release
        cd ${{github.workspace}}/build/release && make vortex -j
        cd ${{github.workspace}}
        dev/examples.sh ${{github.workspace}}/build/release/bin/vortex 0.02

    - name: coverage
      working-directory: ${{github.workspace}}/build/coverage
      run: |
        make unit_coverage

    - name: test
      id: tester
      working-directory: ${{github.workspace}}/build/debug
      run: |
        make unit
    
    - name: report
      if: '!cancelled()'
      working-directory: ${{github.workspace}}/build/debug
      run: |
        cat unit_tests_output.txt
        

    # - name: upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: unit_tests_output.txt
